### ISSUE TITLE
Incompatible with HTTParty because of multi_xml gem requirement

### ISSUE THREAD

**Issue by anthias** [kickstarter/amazon_flex_pay#1]
I'd like to use this gem, but Bundler is complaining about multi_xml version requirements. Is there a reason it's locked to 0.2.0? 

> Bundler could not find compatible versions for gem "multi_xml":
>  In Gemfile:
>    amazon_flex_pay (>= 0) ruby depends on
>      multi_xml (~> 0.2.0) ruby
> 
>    httparty (>= 0) ruby depends on
>      multi_xml (0.5.1)

**Comment by AnatolZaitsev** [comment]
Try to do
```bundle update multi_xml```
